config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :products do
  resources :reviews
end
root to: 'landing#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  before_save(:titleize_product)
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :country_of_origin, presence: true
  validates :cost, presence: true

  scope :most_recent, -> { order(created_at: :desc).limit(3)}
  scope :made_in_usa, -> { where(country_of_origin: "USA")}

  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

    private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  before_save(:titleize_review)

  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true

  private
  def titleize_review
    self.author = self.author.titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
def index
  @most_reviewed = Product.most_reviews
  @recent = Product.most_recent
  @usa = Product.made_in_usa
  render :index
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    @product.save
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
    render :index
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)

    if @product.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Review couldn't be added!"
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    render :edit
  end

  def show
    @review = Review.find(params[:id])
    render :show
  end

  def update
    @review= Review.find(params[:id])
    if @review.update(review_params)
      redirect_to review_path
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  private
    def review_params
      params.require(:review).permit(:author, :rating, :content_body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<h2>Most Reviewed Products</h2>
<% if @most_reviewed.try(:any?) %>
  <ul>
    <% @most_reviewed.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No new products to show.</p>
<% end %>

<h2>Recently Reviewed</h2>
<% if @recent.try(:any?) %>
  <ul>
    <% @recent.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No new products to show.</p>
<% end %>

<h2>American made products</h2>
<% if @usa.try(:any?) %>
  <ul>
    <% @usa.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No new products to show.</p>
<% end %>

<p><%= link_to "View all Products", products_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cost %>
<%= f.number_field :cost, step: :any %>
<%= f.label :country_of_origin %>
<%= f.text_field :country_of_origin %>
<%= f.submit %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
<%= f.label :author %>
<%= f.text_field :author %>
<%= f.label :rating %>
<%= f.number_field :rating, step: 1, min: 1, max: 5 %>
<%= f.label :content_body %>
<%= f.text_area :content_body %>
<p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Mario's</h1>
  <h2>Products</h2>
  <%= link_to "Add a product", new_product_path %>
<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No new products to show.</p>
<% end %>

app/views/products/new.html.erb
<div class="jumbotron">
<h3>Add a product</h3>
</div>
<%= render "layouts/product_form"%>

<%= link_to "Go Back", products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>$<%= @product.cost %></h3>
<h3>Country of origin: <%= @product.country_of_origin %></h3>

<h3>Product Review</h3>
<% if @product.reviews.any? %>
<h4><%= @product.reviews.length %> Reviews</h4>
<% @product.reviews.each do |review| %>
<ul>
  <li>
    <%= review.author %><br>
    <%= review.rating %> stars<br>
    <%= review.content_body %>
  </li>
</ul>
<% end %>
<% else %>
<p>This product has no reviews.</p>
<% end %>

<p><%= link_to "Add review", new_product_review_path(@product) %></p>
<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
  :data => {:confirm => "Are you sure?",
  :method => "delete"} %></p>

<%= link_to "Go Back to all products", products_path %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<% if @review.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @review do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<% if @reviews.any? %>
  <ul>
    <% @reviews.each do |review| %>
      <li><%= link_to review.name, review_path(review.id) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No reviews to show.</p>
<% end %>

<p><%= link_to "Products", products_path %></p>

app/views/reviews/new.html.erb
<div class="jumbotron">
<h3>Add a Review</h3>
</div>
<%= render "layouts/review_form" %>

<%= link_to "Go Back", product_path(@product) %>

app/views/reviews/show.html.erb
<% if @product.reviews.any? %>
<h4><%= @product.reviews.length %> Reviews</h4>
<% @product.reviews.each do |review| %>
<ul>
  <li>
    <%= review.author %><br>
    <%= review.rating %> stars<br>
    <%= review.content_body %>
  </li>
</ul>
<% end %>
<% else %>
<p>This product has no reviews.</p>
<% end %>